### ISSUE TITLE
API Update with new properties

### ISSUE THREAD

**Issue by Alexp2019** [mattmcnabb/OneLogin#46]
This is the updated user class. Preferred_locale_code and manager_user_id
When invoking-restmethod the typecast failed. Might be worth explicitly casting properties via overloaded constructor to prevent future API changes. 

    public class User
    {
        public DateTimeOffset? activated_at { get; set; }
        public string comment { get; set; }
        public string company { get; set; }
        public DateTimeOffset? created_at { get; set; }
        public object[] custom_attributes { get; set; }
        public string department { get; set; }
        public string directory_id {get; set;}
        public string distinguished_name {get; set;}
        public string email {get; set;}
        public string external_id {get; set;}
        public string firstname {get; set;}
        public string group_id {get; set;}
        public string id {get; set;}
        public string invalid_login_attempts {get; set;}
        public DateTimeOffset? invitation_sent_at {get; set;}
        public string lastname {get; set;}
        public DateTimeOffset? last_login {get; set;}
        public string locale_code {get; set;}
		public string preferred_locale_code {get; set;}
        public DateTimeOffset? locked_until {get; set;}
        public string manager_ad_id {get; set;}
		public string manager_user_id {get; set;}
        public string member_of {get; set;}
        public string[] notes {get; set;}
        public string openid_name {get; set;}
        public DateTimeOffset? password_changed_at {get; set;}
        public string phone {get; set;}
        public string[] role_id {get; set;}
        public string samaccountname {get; set;}
        public string state {get; set;}
        public string status {get; set;}
        public string status_value
        {
            get
            {
                try
                {
                    return Enum.GetName(typeof(UserStatus), Int32.Parse(this.status));
                }
                catch
                {
                    return "Unknown";
                }
            }
        }
        public string title {get; set;}
        public string trusted_idp_id {get; set;}
        public DateTimeOffset? updated_at {get; set;}
        public string username {get; set;}
        public string userprincipalname {get; set;}

        public override string ToString() { return this.id; }
    }

**Comment by mattmcnabb** [comment]
@Alexp2019 I'll try to take a look at this change tonight. There are definitely problems with the way classes are implemented here, and it needs to future-proofed a bit.

**Comment by mattmcnabb** [comment]
I'm finally getting around to updating this module a bit. However, to make this work the way I'd like might require a breaking change. I'm also looking at #47, and any other updates to the API's capabilities that I can add PowerShell support for.

**Comment by mattmcnabb** [comment]
@Alexp2019 I was able to fix the issue with unknown properties being returned by the API, and without a breaking change! Please update from the Gallery to version 2.3 and let me know what you think. This change adds a new property to each OneLogin object type called "AdditionalProperties." If any unknown properties are returned by the API their values will be stored here. It will allow us to get to those values and also me know that I should update the module to support the new properties.

Thanks!
